apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crewmeister-challenge.fullname" . }}-grafana-datasource
  labels:
    {{- include "crewmeister-challenge.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-prometheus-server:80
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 5s